# From https://github.com/pages-themes/minimal/tree/master
# On redirections, see also this chat: https://chatgpt.com/c/eec67fbd-3f1e-43af-938c-253207d2d2f7

plugins:
  - jekyll-redirect-from
show_downloads: false
theme: jekyll-theme-minimal
title: J. David Stark's Public Document Shares